### ISSUE TITLE
Error with String parameter in java compiler

### ISSUE THREAD

**Issue by Lyadis** [SINTEF-9012/ThingML#115]
CustomPrint for java in HEADS tutorials does not compile anymore:

```
java.lang.ClassCastException: org.sintef.thingml.impl.ObjectTypeImpl cannot be cast to org.sintef.thingml.PrimitiveType
        at org.thingml.compilers.java.JavaThingImplCompiler.generateMessages(JavaThingImplCompiler.java:98)
        at org.thingml.compilers.java.JavaThingImplCompiler.generateImplementation(JavaThingImplCompiler.java:496)
        at org.thingml.compilers.java.JavaCompiler.do_call_compiler(JavaCompiler.java:106)
        at org.thingml.compilers.utils.OpaqueThingMLCompiler.compile(OpaqueThingMLCompiler.java:65)
        at org.thingml.compilers.commandline.Main.main(Main.java:192)
```

**Comment by Lyadis** [comment]
It's probably caused by the on going work on serialization. JavaThingImplCompiler.java:98 seems to assume that parameter type are always datatype and never object, which is a requirement only for messages exchanged over network, but not for internal communications.

**Comment by brice-morin** [comment]
Yes indeed. Should be easy to fix.
