### ISSUE TITLE
Bad migration of a derived property

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#117]
```
[Error] java.lang.ClassCastException: org.sintef.thingml.impl.SessionImpl cannot be cast to org.sintef.thingml.ParallelRegion
[Error]         at org.sintef.thingml.helpers.ParallelRegionHelper.allContainedSessions(ParallelRegionHelper.java:41)
[Error]         at org.thingml.compilers.java.JavaThingImplCompiler.generateImplementation(JavaThingImplCompiler.java:585)
[Error]         at org.thingml.compilers.java.JavaCompiler.do_call_compiler(JavaCompiler.java:107)
[Error]         at org.thingml.compilers.utils.OpaqueThingMLCompiler.compile(OpaqueThingMLCompiler.java:65)
[Error]         at org.thingml.compilers.commandline.Main.main(Main.java:200)
```

**Comment by brice-morin** [comment]
I guess someone else than @ffleurey fixed this, isn't it @Lyadis ?

**Comment by Lyadis** [comment]
If I am guilty of this fix, it is non intentional...
