### ISSUE TITLE
GraphML export with regions

### ISSUE THREAD

**Issue by brice-morin** [SINTEF-9012/ThingML#30]
Seems that region are not supported in the GraphML export, as YeD explodes when opening a graphml model containing regions:

```
y.H.B.B.a: Target node id Start not defined in this graph!
	at y.H.B.B.Y.Ă(Unknown Source)
	at y.H.B.B.Y.ā(Unknown Source)
	at y.H.B.B.Y.Ć(Unknown Source)
	at y.H.B.B.Y.ā(Unknown Source)
	at y.H.B.B.Y.Ą(Unknown Source)
	at y.H.B.B.Y.ā(Unknown Source)
	at y.H.B.B._.ā(Unknown Source)
	at y.H.B.B._.ā(Unknown Source)
	at y.H.B.A$13.ā(Unknown Source)
	at y.H.B.A.ā(Unknown Source)
	at y.H.B.A.ā(Unknown Source)
	at y.H.Q.ā(Unknown Source)
	at B.A.A.B.G.A.F.ā(Unknown Source)
	at B.A.A.B.G.A.F.ā(Unknown Source)
	at B.A.A.B.G.A.D.ā(Unknown Source)
	at y.H.G.ā(Unknown Source)
	at y.B.A.M.ď(Unknown Source)
	at y.B.W.Č(Unknown Source)
	at y.B.W.ā(Unknown Source)
	at y.B.W.ă(Unknown Source)
	at B.A.A.B.Q.Ă(Unknown Source)
	at B.A.A.B.Q.ā(Unknown Source)
	at B.A.A.J.A.ā(Unknown Source)
	at B.A.A.J.A.ā(Unknown Source)
	at B.A.A.J.D.ă(Unknown Source)
	at B.A.A.J.D.Ă(Unknown Source)
	at B.A.A.B$5.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:727)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.awt.EventQueue$3.run(EventQueue.java:686)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:697)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

```

**Comment by brice-morin** [comment]
Deprecated as we have replaced the graphical export
